remote_theme: marksie1988/jekyll-theme-fresh

title: TotalDebug
url: "https://totaldebug.uk"
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: orange
header:
  title: TotalDebug
  tagline: Technology. Inside Out
  profile_img: /assets/images/logo.png
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; TotalDebug. All rights reserved.'
  links:
    - text: TotalDebug
      url: 'https://totaldebug.uk'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "G-ZDGYQV98HT"
# Fill in your Google adsense ID to implement page ads
autoads_client: "ca-pub-1785931800967089"

plugins:
  - jekyll-remote-theme
  - jekyll-menus
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
