# The Site Configuration

# Import the theme
remote_theme: totaldebug/jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/London

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: TotalDebug # the main title

tagline: Technology. Inside Out # it will display as the sub-title
description: >- # used by seo meta and the atom feed
  Steven Marks. Dev blog. Linux, workflow optimisation, programming, software development, Python, Typescript.
# fill in the base hostname & protocol for your site, e.g., 'https://username.github.io'
url: https://totaldebug.uk

repository: totaldebug/totaldebug.uk

github:
  username: marksie1988 # change to your github username

twitter:
  username: marksie1988 # change to your twitter username

social:
  name: Steven Marks # it will shows as the copyright owner in Footer
  email: noreply@totaldebug.uk # change to your email address
  links:
  # The first element serves as the copyright owner's link
  - https://twitter.com/marksie1988 # change to your twitter homepage
  - https://github.com/marksie1988 # change to your github homepage
  # Uncomment below to add more social links
# - https://www.facebook.com/username
# - https://www.linkedin.com/in/marksie1988

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: G-ZDGYQV98HT # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID

# Pageviews settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
# theme: jekyll-theme-chirpy
# theme_mode:   # [light|dark]
theme_mode: dark

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: ''

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/logo.png

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # Global switch for the post comment system. Keeping it empty means disabled.
  provider: giscus # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: totaldebug/totaldebug.uk # <gh-username>/<repo>
    repo_id: MDEwOlJlcG9zaXRvcnkzMTkxMTkxNTE=
    category: General
    category_id: DIC_kwDOEwVfL84CPpH4
    mapping: # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # the option for PWA feature

# Pagination Settings
paginate: 10

# The base URL of your site
baseurl: ""

post_age_banner:
  enabled: true # Enables banner on posts to show age warning
  age_months: 6 # The age in months for a banner to be shown

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order
  works:
    output: true
    permalink: /works/:title/

defaults:
- scope:
    path: "" # An empty string here means all files in the project
    type: posts
  values:
    layout: post
    comments: true # Enable comments in posts.
    toc: true # Display TOC column in posts.
    # DO NOT modify the following parameter unless you are confident enough
    # to update the code of all other post links in this project.
    permalink: /posts/:title/
- scope:
    path: _works
    type: works
  values:
    layout: work
    comments: false
    toc: false
    permalink: /works/:title/
- scope:
    path: _drafts
  values:
    comments: false
- scope:
    path: ""
    type: tabs # see `site.collections`
  values:
    layout: page
    permalink: /:title/
- scope:
    path: assets/js/dist
  values:
    swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/img/"]
  nested: true
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  gifs: [".gif"]
  regenerate: false
  webp_path: nil
  exclude: []
  append_ext: false

exclude:
- "*.gem"
- "*.gemspec"
- docs
- tools
- README.md
- LICENSE
- rollup.config.js
- package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-archives
- jekyll-remote-theme
- jekyll-sitemap
- jemoji
- jekyll-github-metadata
- jekyll-gist
- jekyll-include-cache
